name: elim_trust_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0' # Make sure this is in quotes

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  dio: ^5.4.0
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  url_launcher: ^6.2.6
  
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.7.0
  animated_text_kit: ^4.2.3
  open_file_plus: ^4.0.1
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - pdf/


